version: 2.1
jobs:
    deploy:
        docker:
            - image: gcr.io/monk-releases/monk-ci:latest
        steps:
            - checkout
            - run:
                command: |
                    MONK="monk -s monkcode://$Monkcode --nofancy --nocolor"
                    $MONK login --email $email --password $pass
                    $MONK ps
workflows:
    build:
        jobs:
            - deploy
                context:
                    - monk

